'use client';

import { CssBaseline } from '@mui/material';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@emotion/react';

import { SoftUIProvider } from '@/context/SoftUI/SoftUIProvider';
import theme from '@/assets/theme/theme';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='es' suppressHydrationWarning={true}>
      <body className={inter.className}>
        <SoftUIProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </SoftUIProvider>
      </body>
    </html>
  );
}
